### PR TITLE
Resolves Failure on Unknown Incompatible with default filter

### LINKED ISSUE #256: Fail on Unknown Incompatible with default filter
Not sure what the desired behaviour should be here but feels wrong to me.

{{ foo | default('bar') }}

When Fail on unknown tokens is set to true and foo doesnt exist in the context this fails with a syntax exception instead of resolving the default filter.

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #256 
Resolves failure on unknown incompatible with default filter.

Checks if the produced result is null and FailOnUnknownTokens in set to true, then only throw the UnknownToken Exception.

had to change the method signature though 😅

### CODE REVIEW

File: src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java [hunk 1]
```diff
@@ -27,8 +16,16 @@
 import com.hubspot.jinjava.interpret.UnknownTokenException;
 import com.hubspot.jinjava.interpret.errorcategory.BasicTemplateErrorCategory;
 import com.hubspot.jinjava.lib.fn.ELFunctionDefinition;
-
 import de.odysseus.el.tree.TreeBuilderException;
+import org.apache.commons.lang3.StringUtils;
```
Comment (boulter) [inline src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: Please revert the import order changes.

File: src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java [hunk 2]
```diff
@@ -72,7 +69,9 @@ public Object resolveExpression(String expression) {
       String elExpression = EXPRESSION_START_TOKEN + expression.trim() + EXPRESSION_END_TOKEN;
       ValueExpression valueExp = expressionFactory.createValueExpression(elContext, elExpression, Object.class);
       Object result = valueExp.getValue(elContext);
-
+      if(result == null && interpreter.getConfig().isFailOnUnknownTokens()) {
```
Comment (boulter) [inline src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: space after `if` please

File: src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java [hunk 3]
```diff
@@ -5,8 +5,8 @@
   private static final long serialVersionUID = -388757722051666198L;
   private final String token;
 
-  public UnknownTokenException(String token, int lineNumber, int startPosition) {
-    super("Unknown token found: " + token, lineNumber, startPosition);
+  public UnknownTokenException(String token) {
```
Comment (boulter) [inline src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: we definitely want to keep these line numbers and positions in the error message.

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java [hunk 4]
```diff
@@ -40,4 +41,21 @@ public void itReplaceTokensWithoutException() {
...
     assertThat(renderedTemplate).isEqualTo("hello test and test1");
   }
+
+  @Test
+  public void itReplacesTokensInContextButThrowsExceptionForOthers() {
+    Map<String, String> context = new HashMap<>();
+    context.put("animal", "lamb");
+    context.put("fruit", "apple");
+    String template = "{{ name }} has a {{ animal }}";
+    try{
```
Comment (boulter) [inline src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: add space after `try`

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java [hunk 5]
```diff
@@ -40,4 +41,21 @@ public void itReplaceTokensWithoutException() {
...
+      jinjava.render(template, context);
+    } catch (Exception ex) {
+      assertThat(ex.getMessage()).containsIgnoringCase("unknown token found");
```
Comment (boulter) [inline src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: this doesn't guarantee that the exception is thrown. You can use `assertThatThrownBy` for that.

File: src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java (hunk 3 above)
Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: since the exception is being thrown at a completely new place now, there seems no way to know the line number and the starting position of the token, hence I changes the method signature.

Let me see if I can make some changes to alter this back to exactly how it was :+1:

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: Screenshot 2019-06-26 at 11 50 02 AM

currently, it doesn't show any lineNumber or startingPosition as well. So I guess removing it is okay?
The above screenshot was taken after I created a test and ran it on the current code in the master branch and it seems not to show the lineNumber and the startingPosition of the variable that is not found.

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java (hunk 5 above)
Comment (gabru-md) [reply src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: okay, will make the changes

File: src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java (hunk 3 above)
Comment (boulter) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: It's not in the `toString()` method, but we use it to build errors when we catch these exceptions.

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java [hunk 6]
```diff
@@ -40,4 +35,25 @@ public void itReplaceTokensWithoutException() {
     String renderedTemplate = jinjava.render(template, context);
     assertThat(renderedTemplate).isEqualTo("hello test and test1");
   }
+
+  @Test
+  public void itReplacesTokensInContextButThrowsExceptionForOthers() {
```
Comment (boulter) [inline src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: could you break this up into two separate tests?

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java [hunk 7]
```diff
@@ -40,4 +35,25 @@ public void itReplaceTokensWithoutException() {
...
+    context.put("fruit", "apple");
+    String template = "{{ name }} has a {{ animal }}";
+
+    Node node = new TreeParser(jinjavaInterpreter, template).buildTree();
+
+    assertThatThrownBy(() -> jinjavaInterpreter.render(node))
+            .isInstanceOf(UnknownTokenException.class)
+            .hasMessageContaining("Unknown token found: name");
+
+
```
Comment (boulter) [inline src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: nit: extra blank lines here

File: src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java (hunk 6 above)
Comment (gabru-md) [reply src/test/java/com/hubspot/jinjava/tree/FailOnUnknownTokensTest.java]: on it :+1:

File: src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java (hunk 2 above)
Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: the problem I'm facing is that when here I do not get the lineNumber and startPosition when I'm about to throw an error here. I only have the expression string with me.

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]:
```java
String elExpression = EXPRESSION_START_TOKEN + expression.trim() + EXPRESSION_END_TOKEN;
      ValueExpression valueExp = expressionFactory.createValueExpression(elContext, elExpression, Object.class);
      Object result = valueExp.getValue(elContext);
      if (result == null && interpreter.getConfig().isFailOnUnknownTokens()) {
        throw new UnknownTokenException(expression);
      }
```

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: should I, in this case, pass -1 and -1 for the same?

Comment (boulter) [reply src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: you have access to the interpreter, so you can use `interpreter.getLineNumber(), interpreter.getPosition()`

**Comment by gabru-md** [comment]
done @boulter

File: src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java (hunk 2 above)
Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/el/ExpressionResolver.java]: done, thanks for the help 😄

File: src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java [hunk 8]
```diff
@@ -5,8 +5,8 @@
   private static final long serialVersionUID = -388757722051666198L;
   private final String token;
 
-  public UnknownTokenException(String token, int lineNumber, int startPosition) {
-    super("Unknown token found: " + token, lineNumber, startPosition);
+  public UnknownTokenException(String token, int lineNumber, int startingPosition) {
```
Comment (boulter) [inline src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: can you remove the changes here?

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: to the method signature?
okay

File: src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java [hunk 9]
```diff
@@ -6,7 +6,7 @@
   private final String token;
 
   public UnknownTokenException(String token, int lineNumber, int startPosition) {
-    super("Unknown token found: " + token, lineNumber, startPosition);
+    super("Unknown token found: " + token.trim(), lineNumber, startPosition);
```
Comment (boulter) [inline src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: do we still need the `trim()`

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: yes. since there was a test that ended up failing because of incorrect padding.
the only way was to trim the token to get rid of the extra space and make the tests pass

Comment (gabru-md) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: [this test](https://github.com/HubSpot/jinjava/pull/345/files#diff-b386f56a1fcb39f707f026174037eab7R152) was failing since the value was coming out to be
`"Unknown token found:  bad " `, where as the expected value is `"Unknown token found: bad"`

therefore I trimmed the token

Comment (boulter) [reply src/main/java/com/hubspot/jinjava/interpret/UnknownTokenException.java]: You can use `hasMessageContaining` instead.
