### PR TITLE
Bind custom operators between `mul` and `unary`

### LINKED ISSUE #893: Unary minus binds too loosely
Consider the following expression:

```
{{ -1 is integer }}
```

I would expect this to evaluate to `true`, since `-1` is an `integer`. However, this actually throws an error.

```
Exception in thread "main" com.hubspot.jinjava.interpret.FatalTemplateErrorsException: Cannot negate 'class java.lang.Boolean'
	at com.hubspot.jinjava.Jinjava.render(Jinjava.java:192)
	at Scratch.main(scratch.java:6)
```

This implies that the unary minus is binding looser than the `is` operator. That is, Jinjava interprets that expression the same as `-(1 is integer)` when it should interpret it as `(-1) is integer`.

### PR DESCRIPTION
**Pull request by tkindy**
Closes #893 

Currently, our custom operators like `|` and `is` bind tighter than unary operators. This means `-1 is integer` incorrectly evaluates like `-(1 is integer)`, leading to an error when Jinjava tries to make `true` negative. This is because these operators are defined within `value` which is called by `unary`, and therefore have precedence greater than the unary operators.

This PR pulls our custom operators up from the `unary` level of the JUEL grammar to the `mul` level. This means they bind tighter than `mul` but less tightly than `unary`. From my testing, this aligns with Jinja's precedence rules.

### CODE REVIEW

File: src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java [hunk 1]
```diff
@@ -427,53 +427,30 @@ protected AstRangeBracket createAstRangeBracket(
   }
 
   @Override
-  protected AstNode value() throws ScanException, ParseException {
```
Comment (tkindy) [inline src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java:430]: This diff is really weird, but basically I moved the parsing of our custom operators from the `default` of `value` to the `default` of `mul`.

**Review by jasmith-hs — CHANGES_REQUESTED** [review]
assertThat(interpreter.render("{{ (-5 * -4 | abs) }}")).isEqualTo("-20");

I think the filter operation should be at the same level as `unary` rather than the same level as mul.
Might make sense to add a new `filter(boolean required)` method and have `mul()` point to that instead of `unary()` and have the filter method call unary and do the `|` and `is` logic

**Comment by tkindy** [comment]
> `assertThat(interpreter.render("{{ (-5 * -4 | abs) }}")).isEqualTo("-20");`

Thanks for the extra test case! I confirmed Jinja indeed returns -20 here.

image

> I think the filter operation should be at the same level as `unary` rather than the same level as mul.

I think you mean filters should bind tighter than `mul` but less tightly than `unary`; that is, that we should introduce a new level of precedence. They currently bind at the same level as `unary`, and that's the problem.

Your implementation suggestion sounds good to me, I'll try that out.

File: src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java (hunk 1 above)
Comment (tkindy) [reply src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java:430]: With my recent changes, the diff makes more sense now.

**Review by jasmith-hs — APPROVED** [review]
LGTM
